Update build_spec.yaml

diff --git a/build_spec.yaml b/build_spec.yaml
--- a/build_spec.yaml
+++ b/build_spec.yaml
@@ -1,23 +1,76 @@
 version: 0.1
 component: build
-timeoutInSeconds: 6000
+timeoutInSeconds: 1000
 shell: bash
-failImmediatelyOnError: true
 env:
+  # these are local variables to the build config
+  variables:
+    BUILD_CACHE_OS_BUCKET_NAME: build-cache
+    BUILD_CACHE_OS_FILE_NAME: m2.zip
+    BUILDX_VERSION: 0.8.2
+
+  vaultVariables:
+    HELM_REPO_USER: ${HELM_REPO_USER}
+    USER_AUTH_TOKEN: ${USER_AUTH_TOKEN}
+
+  # exportedVariables are made available to use as parameters in sucessor Build Pipeline stages
+  # For this Build to run, the Build Pipeline needs to have a BUILDRUN_HASH parameter set
   exportedVariables:
-    - BuildServiceDemoVersion
+    - BUILDRUN_HASH
 
 steps:
   - type: Command
-    timeoutInSeconds: 400
-    name: "Dockerizer"
+    name: "Define unique image tag"
+    timeoutInSeconds: 140
     command: |
-      BuildServiceDemoVersion=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
-      echo $BuildServiceDemoVersion
+      echo "OCI_BUILD_RUN_ID: ${OCI_BUILD_RUN_ID}"
+      export BUILDRUN_HASH=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
+      echo "BUILDRUN_HASH: " $BUILDRUN_HASH
+  - type: Command
+    name: "Docker BuildKit Setup"
+    timeoutInSeconds: 140
+    command: |
+      wget https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 -O docker-buildx
+      mkdir -p ~/.docker/cli-plugins
+      mv docker-buildx ~/.docker/cli-plugins/
+      chmod +x ~/.docker/cli-plugins/docker-buildx
+      docker buildx install
+  - type: Command
+    name: "Build Cache Restore"
+    timeoutInSeconds: 140
+    command: |
+      oci os object head --bucket-name build-cache --name ${BUILD_CACHE_OS_FILE_NAME} > /dev/null 2>&1
+      if [ $? -eq 0 ];
+      then
+        oci os object get --bucket-name build-cache --file ${BUILD_CACHE_OS_FILE_NAME} --name ${BUILD_CACHE_OS_FILE_NAME} && unzip ${BUILD_CACHE_OS_FILE_NAME} -d /tmp
+        echo "Done..."
+      else
+        echo "File not found"
+      fi
+  - type: Command
+    name: "Docker build"
+    command: |
+      export DOCKER_BUILDKIT=1
+      export DOCKER_CLI_EXPERIMENTAL=enabled
       cd backend
-      docker build -t backend
-
+      docker buildx create --use
+      docker buildx build -t backend --cache-from=type=local,src=/tmp/.m2 --cache-to=type=local,dest=/tmp/.m2 --load .
+      echo "DONE"
+    onFailure:
+      - type: Command
+        command: |
+          echo "Handling Failure"
+          build_result=FAILURE
+          echo "Failure successfully handled"
+  - type: Command
+    name: "Build Cache Upload"
+    timeoutInSeconds: 140
+    command: |
+      [ -f ${BUILD_CACHE_OS_FILE_NAME} ] && rm -rf ${BUILD_CACHE_OS_FILE_NAME}
+      cd /tmp
+      zip -r ${BUILD_CACHE_OS_FILE_NAME} .m2
+      oci os object put --bucket-name build-cache --file ${BUILD_CACHE_OS_FILE_NAME} --force
 outputArtifacts:
-  - name: backend
+  - name: APPLICATION_DOCKER_IMAGE
     type: DOCKER_IMAGE
-    location: backend
+    location: backend:latest
